<?php

// function ninghao_demo_form_search_block_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
//   $form['keys']['#placeholder'] = t('搜索');
// }

function ninghao_demo_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'search_block_form') {
    $form['keys']['#placeholder'] = t('搜索');
  }
}

function ninghao_demo_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  $build['#attributes']['class'][] = 'item';
}
